# This handles the building and publishing of the project's release artifacts

name: release-windows
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-02-15
      - name: Build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
        env:
          CURSE_API_TOKEN: ${{ secrets.CURSE_API_TOKEN }}
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/cfmpdlrs1.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
