# This handles the building and publishing of the project's release artifacts

name: release-linux
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-02-15
      - name: Build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
        env:
          CURSE_API_TOKEN: ${{ secrets.CURSE_API_TOKEN }}
      - name: Strip binary
        run: strip target/release/cfmpdlrs1
      - name: Make dist directory
        run: mkdir dist
      - name: Copy binary
        run: cp target/release/cfmpdlrs1 dist/cfmpdlrs1-linux
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/cfmpdlrs1-linux
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
